apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "clickhouse.fullname" . }}-users
# сюда попадает готовый users.xml с пользователями и sha256-хэшами паролей
stringData:
  # файл автоматически подмонтируется в /etc/clickhouse-server/users.d/99-custom-users.xml
  # clickhouse сам подхватит его при старте
  users.xml: |
    <?xml version="1.0"?>
    <clickhouse>
      <users>
        # дефолтный пользователь без пароля 
        <default>
          <password></password>
          <networks><ip>::/0</ip></networks>
          <profile>default</profile>
        </default>
        # пользователи из values.yaml 
        {{- range .Values.users }}
        <{{ .name }}>
          <password_sha256_hex>{{ sha256sum .password }}</password_sha256_hex>
          <networks><ip>::/0</ip></networks>
          <profile>default</profile>
        </{{ .name }}>
        {{- end }}
      </users>
      # профили
      <profiles><default/></profiles>
    </clickhouse>